// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package ethindex

import (
	json "encoding/json"
	common "github.com/ethereum/go-ethereum/common"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonB6915918DecodeGithubComLetamanoirEthindex(in *jlexer.Lexer, out *log) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "address":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Address).UnmarshalJSON(data))
				}
			}
		case "topics":
			if in.IsNull() {
				in.Skip()
				out.Topics = nil
			} else {
				in.Delim('[')
				if out.Topics == nil {
					if !in.IsDelim(']') {
						out.Topics = make([]common.Hash, 0, 2)
					} else {
						out.Topics = []common.Hash{}
					}
				} else {
					out.Topics = (out.Topics)[:0]
				}
				for !in.IsDelim(']') {
					var v1 common.Hash
					if in.IsNull() {
						in.Skip()
					} else {
						if data := in.Raw(); in.Ok() {
							in.AddError((v1).UnmarshalJSON(data))
						}
					}
					out.Topics = append(out.Topics, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "data":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Data).UnmarshalJSON(data))
				}
			}
		case "blockNumber":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.BlockNumber).UnmarshalJSON(data))
				}
			}
		case "transactionHash":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.TxHash).UnmarshalJSON(data))
				}
			}
		case "transactionIndex":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.TxIndex).UnmarshalJSON(data))
				}
			}
		case "blockHash":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.BlockHash).UnmarshalJSON(data))
				}
			}
		case "blockTimestamp":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.BlockTimestamp).UnmarshalJSON(data))
				}
			}
		case "logIndex":
			if in.IsNull() {
				in.Skip()
			} else {
				if data := in.Raw(); in.Ok() {
					in.AddError((out.Index).UnmarshalJSON(data))
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB6915918EncodeGithubComLetamanoirEthindex(out *jwriter.Writer, in log) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"address\":"
		out.RawString(prefix[1:])
		out.RawText((in.Address).MarshalText())
	}
	{
		const prefix string = ",\"topics\":"
		out.RawString(prefix)
		if in.Topics == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Topics {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.RawText((v3).MarshalText())
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"data\":"
		out.RawString(prefix)
		out.RawText((in.Data).MarshalText())
	}
	{
		const prefix string = ",\"blockNumber\":"
		out.RawString(prefix)
		out.RawText((in.BlockNumber).MarshalText())
	}
	{
		const prefix string = ",\"transactionHash\":"
		out.RawString(prefix)
		out.RawText((in.TxHash).MarshalText())
	}
	{
		const prefix string = ",\"transactionIndex\":"
		out.RawString(prefix)
		out.RawText((in.TxIndex).MarshalText())
	}
	{
		const prefix string = ",\"blockHash\":"
		out.RawString(prefix)
		out.RawText((in.BlockHash).MarshalText())
	}
	{
		const prefix string = ",\"blockTimestamp\":"
		out.RawString(prefix)
		out.RawText((in.BlockTimestamp).MarshalText())
	}
	{
		const prefix string = ",\"logIndex\":"
		out.RawString(prefix)
		out.RawText((in.Index).MarshalText())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v log) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB6915918EncodeGithubComLetamanoirEthindex(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v log) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB6915918EncodeGithubComLetamanoirEthindex(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *log) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB6915918DecodeGithubComLetamanoirEthindex(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *log) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB6915918DecodeGithubComLetamanoirEthindex(l, v)
}
